export const INITIAL_STATE = {
  0: {
    id: 0,
    name: "rise_of_broccolini",
    avatar: "https://cdn.fakercloud.com/avatars/xiel_128.jpg",
    jpeg: "http://placeimg.com/640/480/nature",
    caption: "Whatever is good for your soul, do that",
    comments: [],
  },
  1: {
    id: 1,
    name: "rap_scallion",
    avatar: "https://cdn.fakercloud.com/avatars/creartinc_128.jpg",
    jpeg: "http://placeimg.com/640/480/food",
    caption: "Stress less and enjoy the best",
    comments: [],
  },
  2: {
    id: 2,
    name: "squid_game",
    avatar: "https://cdn.fakercloud.com/avatars/melvindidit_128.jpg",
    jpeg: "http://placeimg.com/640/480/sports",
    caption: "Get out there and live a little",
    comments: [],
  },
  3: {
    id: 3,
    name: "averagestudent",
    avatar: "https://cdn.fakercloud.com/avatars/deviljho__128.jpg",
    jpeg: "http://placeimg.com/640/480/abstract",
    caption: "Even the stars were jealous of the sparkle in her eyes",
    comments: [],
  },
  4: {
    id: 4,
    name: "BadKarma",
    avatar: "https://cdn.fakercloud.com/avatars/michigangraham_128.jpg",
    jpeg: "http://placeimg.com/640/480/lorempixel",
    caption: "I’m not high maintenance, you’re just low effort",
    comments: [],
  },
  5: {
    id: 5,
    name: "google_was_my_idea",
    avatar: "https://cdn.fakercloud.com/avatars/perretmagali_128.jpg",
    jpeg: "http://placeimg.com/640/480/city",
    caption: "I’m not gonna sugar coat the truth, I’m not Willy Wonka",
    comments: [],
  },
  6: {
    id: 6,
    name: "cute.as.ducks",
    avatar: "https://cdn.fakercloud.com/avatars/chris_frees_128.jpg",
    jpeg: "http://placeimg.com/640/480/business",
    caption: "Life is better when you’re laughing",
    comments: [],
  },
  7: {
    id: 7,
    name: "casanova",
    avatar: "https://cdn.fakercloud.com/avatars/nateschulte_128.jpg",
    jpeg: "http://placeimg.com/640/480/transport",
    caption: "Look for the magic in every moment",
    comments: [],
  },
  8: {
    id: 8,
    name: "Georgianna",
    avatar: "https://cdn.fakercloud.com/avatars/longlivemyword_128.jpg",
    jpeg: "http://placeimg.com/640/480/animals",
    caption: "A sass a day keeps the basics away",
    comments: [],
  },
  9: {
    id: 9,
    name: "eel_name_hidden",
    avatar: "https://cdn.fakercloud.com/avatars/panghal0_128.jpg",
    jpeg: "http://placeimg.com/640/480/technics",
    caption: "Couldn’t be happier",
    comments: [],
  },
  10: {
    id: 10,
    name: "Joe_slightly_Exotic",
    avatar: "https://cdn.fakercloud.com/avatars/ratbus_128.jpg",
    jpeg: "http://placeimg.com/640/480/abstract",
    caption: "What do you think of this look?",
    comments: [],
  },
  11: {
    id: 11,
    name: "fedora_the_explorer",
    avatar: "https://cdn.fakercloud.com/avatars/brajeshwar_128.jpg",
    jpeg: "http://placeimg.com/640/480/city",
    caption: "Shoutout to myself",
    comments: [],
  },
  12: {
    id: 12,
    name: "MissSnowman",
    avatar: "https://cdn.fakercloud.com/avatars/low_res_128.jpg",
    jpeg: "http://placeimg.com/640/480/fashion",
    caption: "Don’t trust everything you think",
    comments: [],
  },
  13: {
    id: 13,
    name: "Op_nah",
    avatar: "https://cdn.fakercloud.com/avatars/bolzanmarco_128.jpg",
    jpeg: "http://placeimg.com/640/480/animals",
    caption: "When I started counting my blessings",
    comments: [],
  },
  14: {
    id: 14,
    name: "DairyPoppins",
    avatar: "https://cdn.fakercloud.com/avatars/anaami_128.jpg",
    jpeg: "http://placeimg.com/640/480/people",
    caption: "But first, let me take a selfie",
    comments: [],
  },
};

export default INITIAL_STATE;
