export const data = [
  { id: 0 },
  { id: 1 },
  { id: 2 },
  { id: 3 },
  { id: 4 },
  { id: 5 },
  { id: 6 },
  { id: 7 },
  { id: 8 },
  { id: 9 },
  { id: 10 },
  { id: 11 },
  { id: 12 },
  { id: 13 },
  { id: 14 },
];

export const timeArr = [
  "8 HOURS AGO",
  "10 HOURS AGO",
  "14 HOURS AGO",
  "12 HOURS AGO",
  "2 HOURS AGO",
  "3 HOURS AGO",
  "4 HOURS AGO",
  "1 DAY AGO",
  "2 DAYS AGO",
  "6 HOURS AGO",
  "5 HOURS AGO",
  "11 HOURS AGO",
];
